---
title: "Cost & Revenue Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: sandstone
    favicon: favicon.ico
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(reshape2)
library(dplyr)
library(plotly)

pdf(NULL)

cost_rev <- read.csv('cost_rev.csv', header = TRUE)

cost_rev_load <- cost_rev %>%
  filter(grepl("2018", general_ledger_date) )  %>%
    filter(grepl("GRANTS", object_account_description)|
            grepl("CDBG-CITY PLANNING",object_account_description)|
              grepl("OPERATIONAL SUPPLIES",object_account_description)) %>%
                mutate(amount = as.numeric(amount),
                       department_name = as.character(department_name),
                       date_2018 = as.Date(general_ledger_date, "%Y-%m-%d"),
                       cost_center_description = as.character(cost_center_description),
                       fund = as.character(fund_description),
                       X_id = as.factor(X_id))


crInput <- reactive({
  cost_rev <- cost_rev_load %>% 
  #Slider filter
    filter(amount >= input$AmountSelect[1] & amount <= input$AmountSelect[2])
  #Department Filter
  if (length(input$DepartmentSelect) > 0) {
    cost_rev <- subset(cost_rev, department_name %in% input$DepartmentSelect)
  }
  #Account Filter
  if (length(input$AccountSelect) > 0 ) {
    cost_rev <- subset(cost_rev, object_account_description %in% input$AccountSelect)
  }
  #Date Filter
  if (length(input$FundSelect) > 0 ) {
  cost_rev <- subset(cost_rev, fund_description %in% input$FundSelect)
   }
  
  return(cost_rev)
})


# Reactive melted data
  mcrInput <- reactive({
    crInput() %>%
      melt(id = "X_id")
  })
```


Sidebar {.sidebar}
=====================================

```{r}
# Department Selction
selectInput("DepartmentSelect",
            "Department Name:",
            choices = sort(unique(cost_rev_load$department_name)),
            multiple = TRUE,
            selectize = TRUE,
            selected = c("Department of Finance", "DPW-Operations","DPS-Police"))

#fund Select
selectInput("FundSelect",
            "Fund:",
            choices = sort(unique(cost_rev_load$fund_description)),
            multiple = TRUE,
            selectize = TRUE,
            selected = c("GENERAL FUND","SPECIAL PKS PROG/GREAT RACE", "SENIOR CITIZENS PROG TF"))

# Account Selection
checkboxGroupInput("AccountSelect",
                   "Account Size:",
                   choices = sort(unique(cost_rev_load$object_account_description)),
                   selected = c("GRANTS","CDBG-CITY PLANNING","OPERATIONAL SUPPLIES"))
                              
# Amount Selection
sliderInput("AmountSelect",
            "Amount:",
            min = min(cost_rev_load$amount, na.rm = TRUE),
            max = max(cost_rev_load$amount, na.rm = TRUE),
            value = c(min(cost_rev_load$amount,na.rm = TRUE), max(cost_rev_load$amount, na.rm = TRUE)),
            step = 1)                              
                              

```

Plot
=====================================

Row 
-------------------------------------

###

```{r}
renderValueBox({
  cr <- crInput()
  num <- round(mean(cr$amount, na.rm = T), 2)
  valueBox("Avg Cost Amount", value = num, icon = "fa-balance-scale", color = "blue")
})
```

### Department selected

```{r}
renderGauge({
  rate <- round(as.numeric(length(input$DepartmentSelect))/length(unique(cost_rev_load$department_name)) * 100, 1)
  gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
    success = c(70, 100), warning = c(30,69), danger = c(0,29)))
})

```

 Account selected

```{r}
renderGauge({
  rate <- round(as.numeric(length(input$AccountSelect))/length(unique(cost_rev_load$object_account_description)) * 100, 1)
  gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
    success = c(70, 100), warning = c(30,69), danger = c(0,29)))
})

```


Row {.tabset .tabset-fade}
-------------------------------------

### Barplot for Department Name

```{r}
renderPlotly({
  dat <- crInput()
   ggplotly(
      ggplot(data = dat, aes(x = department_name, fill = as.factor(department_name))) + 
        geom_bar() +
        labs(x = "Department Names", title = "Barplot for Department Name") +
        guides(color = FALSE))
})
```

### Point plot for Department Names and Cost Amount

```{r}
renderPlotly({
  dat <- crInput()
  ggplotly(
    ggplot(data = dat, aes(x = department_name, y = amount)) + 
      geom_boxplot() +
      labs(x = " Department Names", y = "Cost Amount", title = "Boxplot for Department Names and Cost Amount") +
      guides(color = FALSE))
})


```

Table
=====================================

Row 
-------------------------------------

### Table 

```{r}
DT::renderDataTable({
  subset(crInput(), select = c(X_id, department_name, date_2018, cost_center_description, amount))
})

```